version: '3.1'

services:

  master-service:
    container_name: master
    image: sync-microservice_master-service:latest
    environment:
      - ARTIFACT_NAME=master-service-0.0.1.jar

  sync-service:
    container_name: sync
    image: sync-microservice_sync-service:latest
    environment:
      - ARTIFACT_NAME=sync-service-0.0.1.jar