version: '3.1'

services:

  nginx-balancer:
    container_name: balancer
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  master-service:
    container_name: master
    restart: unless-stopped
    image: sync-microservice_master-service:latest
    environment:
      - ARTIFACT_NAME=master-service-0.0.1.jar
    depends_on:
      - master-database

  master-database:
    container_name: master-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: master-microservices
    ports:
      - 5588:5432

  sync-service:
    container_name: sync
    restart: unless-stopped
    image: sync-microservice_sync-service:latest
    environment:
      - ARTIFACT_NAME=sync-service-0.0.1.jar
    depends_on:
      - sync-database

  sync-database:
    container_name: sync-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sync-microservices
    ports:
      - 5599:5432